name: Angular Build and Capacitor (Android & iOS)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Upload Web Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: www

  build-android:
    needs: build-angular
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Web Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: www

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Capacitor CLI
        run: npm install @capacitor/core @capacitor/cli

      - name: Sync Capacitor Android
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          npx cap sync android

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Create dummy google-services.json
        run: |
          cat <<EOF > android/app/google-services.json
          {
            "project_info": { "project_number": "123", "project_id": "dummy-project" },
            "client": [{ "client_info": { "mobilesdk_app_id": "1:123:android:abcdef", "android_client_info": { "package_name": "com.example.app" } }, "api_key": [{ "current_key": "dummy-api-key" }] }]
          }
          EOF

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

  build-ios:
    needs: build-angular
    runs-on: macos-latest # iOS requires macOS runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Web Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: www

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Capacitor CLI
        run: npm install @capacitor/core @capacitor/cli

      - name: Sync Capacitor iOS
        run: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
          npx cap sync ios

      - name: Install CocoaPods dependencies
        run: |
          cd ios/App
          pod install

      - name: Build iOS App (Archive)
        run: |
          cd ios
          xcodebuild clean archive \
            -workspace App/App.xcworkspace \
            -scheme App \
            -archivePath App.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Export IPA from Archive
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath App.xcarchive \
            -exportPath ./export \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>method</key><string>development</string><key>signingStyle</key><string>manual</string><key>compileBitcode</key><false/></dict></plist>')

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-ipa
          path: ios/export/App.ipa
