name: Angular Quick Test Pipeline

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  angular-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install ESLint dependencies
        run: |
          npm install --save-dev @angular-eslint/builder @angular-eslint/eslint-plugin @angular-eslint/eslint-plugin-template @angular-eslint/schematics @angular-eslint/template-parser
          npm install --save-dev @typescript-eslint/eslint-plugin @typescript-eslint/parser
          npm install --save-dev eslint eslint-plugin-import

      - name: Create auth.config.ts file
        run: |
          echo 'export const domain = "test-domain.auth0.com";' > src/app/auth.config.ts
          echo 'export const clientId = "test-client-id";' >> src/app/auth.config.ts
          echo 'export const appId = "com.auth0.samples";' >> src/app/auth.config.ts
          echo 'export const auth0Domain = "test-domain.auth0.com";' >> src/app/auth.config.ts
          echo 'const iosOrAndroid = false;' >> src/app/auth.config.ts
          echo 'export const callbackUri = iosOrAndroid ? `${appId}://${auth0Domain}/capacitor/${appId}/callback` : "http://localhost:4200";' >> src/app/auth.config.ts

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Lint Angular App
        run: npm run lint || true  # Continue even if linting fails for now

      - name: Run Unit Tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

      # Capacitor Android APK build steps
      - name: Sync Capacitor Android
        run: |
          npm install @capacitor/core @capacitor/cli
          npx cap add android
          npx cap sync android

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x android/gradlew

      - name: Build Android APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: capacitor-app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk